// design-system/components/forms/SegmentedControl.jsx
import React,{useState,useRef} from 'react';
const h=React.createElement;
const LBL={fontFamily:'var(--font-sans)',fontSize:'var(--size-label,.8125rem)',fontWeight:700,letterSpacing:'var(--track-label,.107em)',textTransform:'uppercase',color:'var(--text-secondary,#46525E)'};
const HELP={fontFamily:'var(--font-mono)',fontSize:'0.75rem',lineHeight:1.5,letterSpacing:'0.04em',color:'var(--text-secondary,#46525E)'};
const ERR={fontFamily:'var(--font-mono)',fontSize:'0.75rem',lineHeight:1.5,letterSpacing:'0.04em',color:'var(--state-error,#A8432D)',textTransform:'uppercase'};

/* Mutually exclusive choice as a frame row — the ClassTimeline weekend/weekday toggle, generalized.
   Replaces circular radios entirely (circles violate the shape law) and iOS switches (on/off rows are
   two-option SegmentedControls: ON / OFF, VISIBLE TO FAMILY / INTERNAL). */
export function SegmentedControl({label,help,error,options=[],value,defaultValue,onChange,disabled=false,fullWidth=false,compact=false,name,style}){
  const opts=options.map(o=>typeof o==='object'?o:{value:o,label:o});
  const [own,setOwn]=useState(defaultValue!==undefined?defaultValue:undefined);
  const cur=value!==undefined?value:own;
  const ids=useRef(null);if(!ids.current)ids.current='mtsg'+Math.random().toString(36).slice(2,7);
  const set=(v)=>{if(disabled)return;if(value===undefined)setOwn(v);onChange&&onChange(v);};
  const onKey=(e)=>{
    const i=opts.findIndex(o=>o.value===cur);
    if(e.key==='ArrowRight'||e.key==='ArrowDown'){e.preventDefault();set(opts[(i+1)%opts.length].value);}
    if(e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();set(opts[(i-1+opts.length)%opts.length].value);}
  };
  return h('div',{style:{display:'flex',flexDirection:'column',gap:8,...style}},
    label&&h('span',{style:LBL,id:ids.current+'-lbl'},label),
    h('div',{role:'radiogroup','aria-labelledby':label?ids.current+'-lbl':undefined,'aria-describedby':error?ids.current+'-err':undefined,onKeyDown:onKey,style:{display:'flex',gap:8,flexWrap:'wrap',opacity:disabled?0.45:1}},
      opts.map((o)=>{const on=o.value===cur;
        return h('button',{key:o.value,type:'button',role:'radio','aria-checked':on,tabIndex:on||cur===undefined&&o===opts[0]?0:-1,disabled,name,
          onClick:()=>set(o.value),
          style:{height:compact?40:48,padding:'0 16px',flex:fullWidth?1:'none',
            border:on?'1px solid var(--ink,#1B1B1B)':'1px solid '+(error?'var(--state-error,#A8432D)':'var(--border-hairline,rgba(27,27,27,0.16))'),
            background:on?'var(--court-050,#EEF3F7)':'transparent',cursor:disabled?'default':'pointer',borderRadius:0,
            fontFamily:'var(--font-mono)',fontSize:'0.6875rem',letterSpacing:'0.08em',fontWeight:on?600:400,
            color:'var(--ink,#1B1B1B)',textTransform:'uppercase',transition:'background var(--dur-fast,120ms) var(--ease-out,ease)'}},o.label);})),
    help&&h('span',{style:HELP},help),
    error&&h('span',{id:ids.current+'-err',role:'alert',style:ERR},'ERROR: ',error));
}

// src/lib/ds/forms/SegmentedControl.svelte
<script lang="ts">
	import FieldShell from './FieldShell.svelte';

	/* Mutually exclusive choice as a frame row — the ClassTimeline weekend/weekday toggle, generalized.
	   Replaces circular radios entirely (circles violate the shape law) and iOS switches (on/off rows
	   are two-option SegmentedControls: ON / OFF, VISIBLE TO FAMILY / INTERNAL). */
	type Option = string | { value: string; label: string };
	let {
		label,
		help,
		error,
		options = [],
		value = $bindable(),
		onchange,
		disabled = false,
		fullWidth = false,
		compact = false,
		name,
		id
	}: {
		label?: string;
		help?: string;
		error?: string;
		/** string[] or {value, label}[] — 2–5 short options */
		options?: Option[];
		value?: string;
		/** Called with the option value */
		onchange?: (value: string) => void;
		disabled?: boolean;
		/** Options stretch to fill the row */
		fullWidth?: boolean;
		/** 40px frames (inside dense cards) instead of 48px */
		compact?: boolean;
		/** When set, a hidden input submits the value with native forms */
		name?: string;
		id?: string;
	} = $props();

	const uid = $props.id();
	const fieldId = $derived(id ?? `mtsg-${uid}`);
	const opts = $derived(options.map((o) => (typeof o === 'object' ? o : { value: o, label: o })));

	function set(v: string) {
		if (disabled) return;
		value = v;
		onchange?.(v);
	}
	function onKey(e: KeyboardEvent) {
		const i = opts.findIndex((o) => o.value === value);
		if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
			e.preventDefault();
			set(opts[(i + 1) % opts.length].value);
		}
		if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
			e.preventDefault();
			set(opts[(i - 1 + opts.length) % opts.length].value);
		}
	}
</script>

<FieldShell id={fieldId} {label} {help} {error} labelAs="span">
	{#snippet children({ describedBy, invalid, labelId })}
		<div
			class="mt-seg"
			class:mt-seg--disabled={disabled}
			role="radiogroup"
			tabindex="-1"
			aria-labelledby={label ? labelId : undefined}
			aria-describedby={describedBy}
			onkeydown={onKey}
		>
			{#each opts as o, i (o.value)}
				{@const on = o.value === value}
				<button
					type="button"
					role="radio"
					aria-checked={on}
					tabindex={on || (value === undefined && i === 0) ? 0 : -1}
					class="mt-seg__opt"
					class:mt-seg__opt--on={on}
					class:mt-seg__opt--error={invalid && !on}
					class:mt-seg__opt--full={fullWidth}
					class:mt-seg__opt--compact={compact}
					{disabled}
					onclick={() => set(o.value)}>{o.label}</button
				>
			{/each}
		</div>
		{#if name}<input type="hidden" {name} value={value ?? ''} />{/if}
	{/snippet}
</FieldShell>

<style>
	.mt-seg {
		display: flex;
		gap: var(--space-2);
		flex-wrap: wrap;
	}
	.mt-seg--disabled {
		opacity: 0.45;
	}
	.mt-seg__opt {
		height: var(--size-action);
		padding: 0 16px;
		flex: none;
		border: 1px solid var(--border-hairline);
		background: transparent;
		cursor: pointer;
		border-radius: var(--radius-none);
		font-family: var(--font-mono);
		font-size: 0.6875rem;
		letter-spacing: 0.08em;
		font-weight: var(--weight-regular);
		color: var(--ink);
		text-transform: uppercase;
		transition: background var(--dur-fast) var(--ease-out);
	}
	.mt-seg__opt--on {
		border-color: var(--ink);
		background: var(--court-050);
		font-weight: 600;
	}
	.mt-seg__opt--error {
		border-color: var(--state-error);
	}
	.mt-seg__opt--full {
		flex: 1;
	}
	.mt-seg__opt--compact {
		height: 40px;
	}
	.mt-seg--disabled .mt-seg__opt {
		cursor: default;
	}
</style>
