// design-system/components/feedback/Pagination.jsx
import React from 'react';
const h=React.createElement;
const pad=n=>String(n).padStart(2,'0');

/* Mono 01 / 04 with typographic ghost prev/next. */
export function Pagination({page=1,pages=1,onChange,style}){
  const btn=(dir,lab,disabled)=>h('button',{type:'button','aria-label':lab,disabled,onClick:()=>onChange&&onChange(page+dir),
    style:{width:44,height:44,background:'none',border:'none',cursor:disabled?'default':'pointer',opacity:disabled?0.35:1,
      fontFamily:'var(--font-mono)',fontSize:'0.9375rem',color:'var(--ink,#1B1B1B)',borderRadius:0}},dir<0?'\u2190':'\u2192');
  return h('nav',{'aria-label':'Pagination',style:{display:'inline-flex',alignItems:'center',gap:8,...style}},
    btn(-1,'Previous page',page<=1),
    h('span',{'aria-live':'polite',style:{fontFamily:'var(--font-mono)',fontSize:'0.75rem',letterSpacing:'0.07em',color:'var(--text-secondary,#46525E)'}},pad(page)+' / '+pad(pages)),
    btn(1,'Next page',page>=pages));
}

// src/lib/ds/feedback/Pagination.svelte
<script lang="ts">
	/* Mono 01 / 04 with typographic ghost prev/next. 44px targets, ends disabled. */
	let {
		page = 1,
		pages = 1,
		onchange
	}: { page?: number; pages?: number; onchange?: (page: number) => void } = $props();
	const pad = (n: number) => String(n).padStart(2, '0');
</script>

<nav class="mt-pager" aria-label="Pagination">
	<button
		type="button"
		class="mt-pager__btn"
		aria-label="Previous page"
		disabled={page <= 1}
		onclick={() => onchange?.(page - 1)}>&#x2190;</button
	>
	<span class="mt-pager__count" aria-live="polite">{pad(page)} / {pad(pages)}</span>
	<button
		type="button"
		class="mt-pager__btn"
		aria-label="Next page"
		disabled={page >= pages}
		onclick={() => onchange?.(page + 1)}>&#x2192;</button
	>
</nav>

<style>
	.mt-pager {
		display: inline-flex;
		align-items: center;
		gap: var(--space-2);
	}
	.mt-pager__btn {
		width: 44px;
		height: 44px;
		background: none;
		border: none;
		cursor: pointer;
		font-family: var(--font-mono);
		font-size: 0.9375rem;
		color: var(--ink);
		border-radius: var(--radius-none);
	}
	.mt-pager__btn[disabled] {
		cursor: default;
		opacity: 0.35;
	}
	.mt-pager__count {
		font-family: var(--font-mono);
		font-size: var(--size-label-sm);
		letter-spacing: 0.07em;
		color: var(--text-secondary);
	}
</style>
