// design-system/components/site/ClassTimeline.jsx
import React,{useState} from 'react';

const DEFAULT_BLOCKS=[
  {title:'Technical skill training',desc:'Footwork, grip, swing shape — one element isolated and repeated until you can see it.'},
  {title:'Dynamic drills & skill application',desc:'The same technique under movement and pressure: live feeds, patterns, decision speed.'},
  {title:'Gameplay & strategy',desc:'Point construction, scoring, match habits — the skill applied where it counts.'}
];
const CHIPS=['#A9BDC9','#3E6C99','#1C3655'];

/* One class, play by play: three equal blocks. Weekends run 2h (40-min blocks), weekdays 1.5h (30-min).
   Wall-clock start times are set by the academy (admin console) — the timeline shows offsets, not clock times. */
export function ClassTimeline({variant='weekend',showToggle=true,blocks=DEFAULT_BLOCKS,style}){
  const [v,setV]=useState(variant);
  const [now,setNow]=useState(-1);
  const per=v==='weekend'?40:30;
  const off=(i)=>{const t=i*per;return 'T+'+Math.floor(t/60)+':'+String(t%60).padStart(2,'0');};
  const segBtn=(key,label)=>React.createElement('button',{key,onClick:()=>setV(key),'aria-pressed':v===key,style:{
    height:40,padding:'0 16px',border:v===key?'1px solid var(--ink,#1B1B1B)':'1px solid var(--border-hairline,rgba(27,27,27,0.16))',
    background:v===key?'var(--court-050,#EEF3F7)':'transparent',cursor:'pointer',fontFamily:'var(--font-mono)',
    fontSize:'0.6875rem',letterSpacing:'0.08em',fontWeight:v===key?600:400,color:'var(--ink,#1B1B1B)',textTransform:'uppercase',borderRadius:0}},label);
  return React.createElement('div',{style},
    showToggle&&React.createElement('div',{role:'group','aria-label':'Class length',style:{display:'flex',gap:8,marginBottom:8}},
      segBtn('weekend','Weekend · 2h'),segBtn('weekday','Weekday · 1.5h')),
    React.createElement('ol',{style:{listStyle:'none',margin:0,padding:0}},
      blocks.map((b,i)=>{
        const active=now===i;
        return React.createElement('li',{key:i,tabIndex:0,onMouseEnter:()=>setNow(i),onMouseLeave:()=>setNow(-1),onFocus:()=>setNow(i),onBlur:()=>setNow(-1),
          style:{display:'grid',gridTemplateColumns:'58px 40px 1fr',gap:'0 16px',alignItems:'start',position:'relative',padding:'14px 8px',background:active?'var(--surface-tint,#EEF3F7)':'transparent',transition:'background var(--dur-fast,120ms) var(--ease-out,ease)',outlineOffset:2}},
          i<blocks.length-1&&React.createElement('span',{'aria-hidden':true,style:{position:'absolute',left:58+16+19,top:54,bottom:-14,width:1,background:'var(--border-hairline,rgba(27,27,27,0.16))'}}),
          React.createElement('span',{style:{fontFamily:'var(--font-mono)',fontSize:'0.8125rem',color:'var(--text-secondary,#46525E)',paddingTop:11}},off(i)),
          React.createElement('span',{'aria-hidden':true,style:{width:40,height:40,display:'grid',placeItems:'center',fontFamily:'var(--font-mono)',fontSize:'0.8125rem',fontWeight:600,background:active?'var(--now,#E8A33D)':CHIPS[i]||CHIPS[2],color:active?'var(--ink,#1B1B1B)':i===0?'var(--court-800,#1C3655)':'var(--line-white,#F7F7F7)',transition:'background var(--dur-fast,120ms) var(--ease-out,ease)',position:'relative',zIndex:1}},String(i+1).padStart(2,'0')),
          React.createElement('div',{style:{display:'flex',flexDirection:'column',gap:3,paddingTop:8}},
            React.createElement('div',{style:{display:'flex',justifyContent:'space-between',gap:16,alignItems:'baseline'}},
              React.createElement('span',{style:{fontFamily:'var(--font-sans)',fontSize:'var(--size-body,1rem)',fontWeight:600,color:'var(--ink,#1B1B1B)'}},b.title),
              React.createElement('span',{style:{fontFamily:'var(--font-mono)',fontSize:'0.6875rem',letterSpacing:'0.107em',textTransform:'uppercase',color:active?'var(--accent-present-hover,#C77F14)':'var(--court-400,#3E6C99)',whiteSpace:'nowrap'}},per+' MIN')
            ),
            b.desc&&React.createElement('span',{style:{fontFamily:'var(--font-sans)',fontSize:'var(--size-body-sm,.875rem)',lineHeight:1.5,color:'var(--text-secondary,#46525E)',maxWidth:'52ch'}},b.desc)
          )
        );
      })
    ),
    React.createElement('div',{style:{borderTop:'1px solid var(--border-hairline,rgba(27,27,27,0.16))',marginTop:4,paddingTop:12,fontFamily:'var(--font-mono)',fontSize:'0.6875rem',letterSpacing:'0.07em',color:'var(--text-secondary,#46525E)',textTransform:'uppercase'}},
      '3 blocks · '+per+' min each · '+(v==='weekend'?'2h — weekends':'1.5h — weekdays')+' · times set by the academy')
  );
}

// src/lib/ds/site/ClassTimeline.svelte
<script lang="ts">
	/* One class, play by play: three equal sequential blocks. Weekends run 2h (3×40 min), weekdays
	   1.5h (3×30 min). Wall-clock start times are set by the academy in the admin console, so this
	   shows T+ offsets and never a clock time. The hovered block goes amber = "now".

	   The reference puts each row in the tab order so focus can flip the frame too. It is dropped
	   here: nothing in a row is actionable, every value is already text, and five dead tab stops
	   cost a keyboard user more than the amber gains them. */
	type Block = { title: string; desc?: string };

	const DEFAULT_BLOCKS: Block[] = [
		{
			title: 'Technical skill training',
			desc: 'Footwork, grip, swing shape — one element isolated and repeated until you can see it.'
		},
		{
			title: 'Dynamic drills & skill application',
			desc: 'The same technique under movement and pressure: live feeds, patterns, decision speed.'
		},
		{
			title: 'Gameplay & strategy',
			desc: 'Point construction, scoring, match habits — the skill applied where it counts.'
		}
	];

	let {
		variant = 'weekend',
		showToggle = true,
		blocks = DEFAULT_BLOCKS
	}: {
		/** Initial length: 'weekend' (2h) or 'weekday' (1.5h) */
		variant?: 'weekend' | 'weekday';
		showToggle?: boolean;
		blocks?: Block[];
	} = $props();

	// the prop is the INITIAL length per the contract; the toggle owns it afterwards
	// svelte-ignore state_referenced_locally
	let current = $state(variant);
	const per = $derived(current === 'weekend' ? 40 : 30);
	const offset = (i: number) => {
		const t = i * per;
		return `T+${Math.floor(t / 60)}:${String(t % 60).padStart(2, '0')}`;
	};
</script>

<div class="mt-clt">
	{#if showToggle}
		<div class="mt-clt__toggle" role="group" aria-label="Class length">
			<button
				type="button"
				class="mt-clt__seg"
				class:mt-clt__seg--on={current === 'weekend'}
				aria-pressed={current === 'weekend'}
				onclick={() => (current = 'weekend')}>Weekend · 2h</button
			>
			<button
				type="button"
				class="mt-clt__seg"
				class:mt-clt__seg--on={current === 'weekday'}
				aria-pressed={current === 'weekday'}
				onclick={() => (current = 'weekday')}>Weekday · 1.5h</button
			>
		</div>
	{/if}

	<ol class="mt-clt__list">
		{#each blocks as b, i (i)}
			<li class="mt-clt__item">
				{#if i < blocks.length - 1}<span class="mt-clt__rule" aria-hidden="true"></span>{/if}
				<span class="mt-clt__offset">{offset(i)}</span>
				<span class="mt-clt__chip mt-clt__chip--{i + 1}" aria-hidden="true"
					>{String(i + 1).padStart(2, '0')}</span
				>
				<div class="mt-clt__body">
					<div class="mt-clt__row">
						<span class="mt-clt__title">{b.title}</span>
						<span class="mt-clt__len">{per} MIN</span>
					</div>
					{#if b.desc}<span class="mt-clt__desc">{b.desc}</span>{/if}
				</div>
			</li>
		{/each}
	</ol>

	<div class="mt-clt__foot">
		3 blocks · {per} min each · {current === 'weekend' ? '2h — weekends' : '1.5h — weekdays'} · times
		set by the academy
	</div>
</div>

<style>
	.mt-clt__toggle {
		display: flex;
		gap: var(--space-2);
		margin-bottom: var(--space-2);
	}
	.mt-clt__seg {
		height: 40px;
		padding: 0 16px;
		border: var(--hairline);
		background: transparent;
		cursor: pointer;
		font-family: var(--font-mono);
		font-size: 0.6875rem;
		letter-spacing: 0.08em;
		color: var(--ink);
		text-transform: uppercase;
		border-radius: var(--radius-none);
	}
	.mt-clt__seg--on {
		border-color: var(--ink);
		background: var(--court-050);
		font-weight: var(--weight-medium);
	}
	.mt-clt__list {
		list-style: none;
		margin: 0;
		padding: 0;
	}
	.mt-clt__item {
		display: grid;
		grid-template-columns: 58px 40px 1fr;
		gap: 0 16px;
		align-items: start;
		position: relative;
		padding: 14px 8px;
		background: transparent;
		transition: background var(--dur-fast) var(--ease-out);
		outline-offset: 2px;
	}
	.mt-clt__item:hover {
		background: var(--surface-tint);
	}
	.mt-clt__rule {
		position: absolute;
		left: 93px;
		top: 54px;
		bottom: -14px;
		width: 1px;
		background: var(--border-hairline);
	}
	.mt-clt__offset {
		font-family: var(--font-mono);
		font-size: 0.8125rem;
		color: var(--text-secondary);
		padding-top: 11px;
	}
	.mt-clt__chip {
		width: 40px;
		height: 40px;
		display: grid;
		place-items: center;
		font-family: var(--font-mono);
		font-size: 0.8125rem;
		font-weight: var(--weight-medium);
		position: relative;
		z-index: 1;
		transition: background var(--dur-fast) var(--ease-out);
	}
	.mt-clt__chip--1 {
		background: var(--court-200);
		color: var(--court-800);
	}
	.mt-clt__chip--2 {
		background: var(--court-400);
		color: var(--line-white);
	}
	.mt-clt__chip--3 {
		background: var(--court-800);
		color: var(--line-white);
	}
	.mt-clt__item:hover .mt-clt__chip {
		background: var(--now);
		color: var(--ink);
	}
	.mt-clt__body {
		display: flex;
		flex-direction: column;
		gap: 3px;
		padding-top: var(--space-2);
	}
	.mt-clt__row {
		display: flex;
		justify-content: space-between;
		gap: var(--space-4);
		align-items: baseline;
	}
	.mt-clt__title {
		font-family: var(--font-sans);
		font-size: var(--size-body);
		font-weight: var(--weight-medium);
		color: var(--ink);
	}
	.mt-clt__len {
		font-family: var(--font-mono);
		font-size: 0.6875rem;
		letter-spacing: var(--track-label);
		text-transform: uppercase;
		color: var(--court-400);
		white-space: nowrap;
	}
	.mt-clt__item:hover .mt-clt__len {
		color: var(--accent-present-hover);
	}
	.mt-clt__desc {
		font-family: var(--font-sans);
		font-size: var(--size-body-sm);
		line-height: 1.5;
		color: var(--text-secondary);
		max-width: 52ch;
	}
	.mt-clt__foot {
		border-top: var(--hairline);
		margin-top: 4px;
		padding-top: var(--space-3);
		font-family: var(--font-mono);
		font-size: 0.6875rem;
		letter-spacing: 0.07em;
		color: var(--text-secondary);
		text-transform: uppercase;
	}
</style>
