// src/lib/ds/forms/Checkbox.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { HTMLInputAttributes } from 'svelte/elements';

	/* A frame that fills: hairline square, solid ink when checked — the attendance-strip squares
	   are the precedent (fill-state carries the meaning, not color). consent variant: larger frame +
	   body-copy label, for waiver signing. 44px minimum target. */
	type Props = {
		label?: string | Snippet;
		checked?: boolean;
		/** Large 28px frame + body label — waiver/consent rows */
		consent?: boolean;
		/** Renders "ERROR: <message>" + --state-error frame border */
		error?: string;
		id?: string;
	} & Omit<HTMLInputAttributes, 'checked' | 'type' | 'id'>;

	let {
		label,
		checked = $bindable(false),
		consent = false,
		error,
		id,
		disabled = false,
		...rest
	}: Props = $props();

	const uid = $props.id();
	const fieldId = $derived(id ?? `mtc-${uid}`);
</script>

<div class="mt-check" class:mt-check--consent={consent} class:mt-check--disabled={disabled}>
	<label class="mt-check__row" for={fieldId}>
		<span class="mt-check__box">
			<input
				bind:checked
				id={fieldId}
				type="checkbox"
				class="mt-check-input"
				{disabled}
				aria-invalid={error ? true : undefined}
				aria-describedby={error ? `${fieldId}-err` : undefined}
				{...rest}
			/>
			<span
				class="mt-check-frame"
				class:mt-check-frame--on={checked}
				class:mt-check-frame--error={Boolean(error)}
				aria-hidden="true"
			></span>
		</span>
		{#if label}
			<span class="mt-check__label">
				{#if typeof label === 'string'}{label}{:else}{@render label()}{/if}
			</span>
		{/if}
	</label>
	{#if error}<span class="mt-check__error" id="{fieldId}-err" role="alert">ERROR: {error}</span
		>{/if}
</div>

<style>
	.mt-check {
		display: flex;
		flex-direction: column;
		gap: var(--space-2);
	}
	.mt-check__row {
		display: flex;
		gap: var(--space-3);
		align-items: flex-start;
		min-height: 44px;
		cursor: pointer;
		padding: 2px 0;
	}
	.mt-check--consent .mt-check__row {
		gap: 14px;
	}
	.mt-check--disabled .mt-check__row {
		cursor: default;
		opacity: 0.45;
	}
	.mt-check__box {
		position: relative;
		flex: none;
		width: 20px;
		height: 20px;
		margin-top: 1px;
	}
	.mt-check--consent .mt-check__box {
		width: 28px;
		height: 28px;
		margin-top: 2px;
	}
	.mt-check-input {
		position: absolute;
		opacity: 0;
		margin: 0;
		width: 100%;
		height: 100%;
		cursor: pointer;
	}
	.mt-check-input[disabled] {
		cursor: default;
	}
	.mt-check-input:focus-visible + .mt-check-frame {
		outline: 2px solid var(--focus-on-light);
		outline-offset: 2px;
	}
	.mt-check-frame {
		position: absolute;
		inset: 0;
		box-sizing: border-box;
		border: 1px solid rgba(27, 27, 27, 0.4);
		background: var(--white);
		transition: background var(--dur-fast) var(--ease-out);
	}
	.mt-check-frame--on {
		border-color: var(--ink);
		background: var(--ink);
	}
	.mt-check-frame--error {
		border-color: var(--state-error);
	}
	.mt-check__label {
		font-family: var(--font-sans);
		font-size: var(--size-body-sm);
		line-height: 1.5;
		color: var(--ink);
		align-self: center;
	}
	.mt-check--consent .mt-check__label {
		line-height: var(--leading-body);
		align-self: auto;
	}
	.mt-check__error {
		font-family: var(--font-mono);
		font-size: var(--size-label-sm);
		line-height: 1.5;
		letter-spacing: 0.04em;
		color: var(--state-error);
		text-transform: uppercase;
	}
</style>

// design-system/components/forms/Checkbox.jsx
import React,{useState,useRef} from 'react';
const h=React.createElement;
const ERR={fontFamily:'var(--font-mono)',fontSize:'0.75rem',lineHeight:1.5,letterSpacing:'0.04em',color:'var(--state-error,#A8432D)',textTransform:'uppercase'};
function ensureStyles(){
  if(typeof document==='undefined'||document.getElementById('mt-check-styles'))return;
  const s=document.createElement('style');s.id='mt-check-styles';
  s.textContent=`
.mt-check-input{position:absolute;opacity:0;margin:0;width:100%;height:100%;cursor:pointer}
.mt-check-input:focus-visible+.mt-check-frame{outline:2px solid var(--focus-on-light,#2B5680);outline-offset:2px}
.mt-check-input[disabled]{cursor:default}`;
  document.head.appendChild(s);
}

/* A frame that fills: hairline square, solid ink when checked — the attendance-strip squares are the precedent.
   consent variant: larger frame + body-copy label, for waiver signing. */
export function Checkbox({label,checked,defaultChecked,onChange,disabled=false,consent=false,error,name,style}){
  ensureStyles();
  const [own,setOwn]=useState(!!defaultChecked);
  const isOn=checked!==undefined?checked:own;
  const ids=useRef(null);if(!ids.current)ids.current='mtc'+Math.random().toString(36).slice(2,7);
  const size=consent?28:20;
  return h('div',{style:{display:'flex',flexDirection:'column',gap:8,...style}},
    h('label',{style:{display:'flex',gap:consent?14:12,alignItems:'flex-start',minHeight:44,cursor:disabled?'default':'pointer',opacity:disabled?0.45:1,padding:'2px 0'}},
      h('span',{style:{position:'relative',flex:'none',width:size,height:size,marginTop:consent?2:1}},
        h('input',{type:'checkbox',className:'mt-check-input',name,checked:checked!==undefined?checked:undefined,defaultChecked:checked===undefined?defaultChecked:undefined,disabled,
          'aria-invalid':error?true:undefined,'aria-describedby':error?ids.current+'-err':undefined,
          onChange:(e)=>{if(checked===undefined)setOwn(e.target.checked);onChange&&onChange(e);}}),
        h('span',{className:'mt-check-frame','aria-hidden':true,style:{position:'absolute',inset:0,boxSizing:'border-box',
          border:'1px solid '+(error?'var(--state-error,#A8432D)':isOn?'var(--ink,#1B1B1B)':'rgba(27,27,27,0.4)'),
          background:isOn?'var(--ink,#1B1B1B)':'var(--white,#fff)',transition:'background var(--dur-fast,120ms) var(--ease-out,ease)'}})),
      label&&h('span',{style:consent?{fontFamily:'var(--font-sans)',fontSize:'var(--size-body-sm,.875rem)',lineHeight:1.55,color:'var(--ink,#1B1B1B)'}:{fontFamily:'var(--font-sans)',fontSize:'var(--size-body-sm,.875rem)',lineHeight:1.5,color:'var(--ink,#1B1B1B)',alignSelf:'center'}},label)),
    error&&h('span',{id:ids.current+'-err',role:'alert',style:ERR},'ERROR: ',error));
}
