// design-system/components/core/Eyebrow.jsx
import React from 'react';
import {FrameTicks} from '../brand/FrameTicks.jsx';

/* The speaking voice: uppercase, 13px, 0.107em. Optionally led by frame ticks. */
export function Eyebrow({children,onField=false,ticks=false,style}){
  return React.createElement('div',{style:{display:'flex',alignItems:'center',gap:12,fontFamily:'var(--font-sans)',fontSize:'var(--size-label,.8125rem)',fontWeight:700,letterSpacing:'var(--track-label,.107em)',textTransform:'uppercase',color:onField?'var(--text-on-field-dim,#A9BDC9)':'var(--court-500,#2B5680)',...style}},
    ticks&&React.createElement(FrameTicks,{size:7,tone:onField?'field':'light'}),
    React.createElement('span',null,children)
  );
}

// src/lib/ds/core/Eyebrow.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import FrameTicks from './FrameTicks.svelte';

	/* The speaking voice: uppercase, 13px, 0.107em. Optionally led by frame ticks. */
	let {
		onField = false,
		ticks = false,
		children
	}: { onField?: boolean; ticks?: boolean; children: Snippet } = $props();
</script>

<div class="mt-eyebrow mt-eyebrow-row" class:mt-eyebrow-row--field={onField}>
	{#if ticks}<FrameTicks size={7} tone={onField ? 'field' : 'light'} />{/if}
	<span>{@render children()}</span>
</div>

<style>
	.mt-eyebrow-row {
		display: flex;
		align-items: center;
		gap: var(--space-3);
		color: var(--court-500);
	}
	.mt-eyebrow-row--field {
		color: var(--text-on-field-dim);
	}
</style>
