// src/lib/ds/feedback/EmptyState.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import FrameTicks from '../core/FrameTicks.svelte';

	/* The mono-line empty convention codified (NO SESSIONS — COURTS REST ON WED & FRI).
	   All-cool ticks: nothing is "now". */
	let {
		ticks = false,
		action,
		children
	}: { ticks?: boolean; action?: Snippet; children?: Snippet } = $props();
</script>

<div class="mt-empty">
	{#if ticks}<FrameTicks active="none" />{/if}
	<p class="mt-empty__line">{@render children?.()}</p>
	{#if action}<div>{@render action()}</div>{/if}
</div>

<style>
	.mt-empty {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 14px;
		padding: 40px 24px;
		text-align: center;
	}
	.mt-empty__line {
		margin: 0;
		font-family: var(--font-mono);
		font-size: var(--size-label-sm);
		line-height: 1.7;
		letter-spacing: 0.05em;
		text-transform: uppercase;
		color: var(--text-secondary);
		max-width: 44ch;
	}
</style>

// design-system/components/feedback/EmptyState.jsx
import React from 'react';
import {FrameTicks} from '../brand/FrameTicks.jsx';
const h=React.createElement;

/* The mono-line empty convention codified (NO SESSIONS — COURTS REST ON WED & FRI). */
export function EmptyState({children,ticks=false,action,style}){
  return h('div',{style:{display:'flex',flexDirection:'column',alignItems:'center',gap:14,padding:'40px 24px',textAlign:'center',...style}},
    ticks&&h(FrameTicks,{active:'none'}),
    h('p',{style:{margin:0,fontFamily:'var(--font-mono)',fontSize:'0.75rem',lineHeight:1.7,letterSpacing:'0.05em',textTransform:'uppercase',color:'var(--text-secondary,#46525E)',maxWidth:'44ch'}},children),
    action&&h('div',null,action));
}
